### ISSUE TITLE
Using `anstream` in tandem with Rust 1.70's `std::io::IsTerminal` trait

### ISSUE THREAD

**Issue by mataha** [rust-cli/anstyle#109]
Rust 1.70 introduced the [IsTerminal](https://doc.rust-lang.org/std/io/trait.IsTerminal.html) trait and with it `is_terminal()` method.

Can it be used in `anstream` in place of `is-terminal` (as `anstream` depends on `std` already), or is that a no-go due to `IsTerminal` being sealed? (This would bump the MSRV of course, which is another potential concern.)

**Comment by epage** [comment]
We'll have to rework some things but we plan to switch when 1.72 is out

**Comment by mataha** [comment]
`anstream` 0.5.0 does this, thanks!
