### ISSUE TITLE
Guidance re debugging

### ISSUE THREAD

**Issue by max-sixty** [rust-cli/anstyle#111]
We recently got an issue re colors being printed when they shouldn't be — https://github.com/PRQL/prql/issues/3285.

Would you have any guidance for how to handle these?

I can see a few possible sources of error:
- PRQL library not using `anstream` correctly
- A misconfiguration on the user side — e.g. the terminal states that it supports colors but doesn't
- A bug in `anstream`

Is there some command we could ask someone to run to help assess whether it's a misconfiguration? i.e. "run this, it might show that your terminal reports that it can handle colors". It could even give the reason that colors are being printed — i.e. "`CLI_COLOR=1` so we're printing colors".

Or any other guidance? At the moment I'm not sure what to say beyond "meh maybe a bug maybe not"...

Thanks, and appreciate the patience with the open-ended question.

**Comment by epage** [comment]
If they can run
```console
$ cargo install anstyle-query --examples --root anstyle-query
$ anstyle-query/bin/report
clicolor: None
clicolor_force: false
no_color: false
term_supports_ansi_color: true
term_supports_color: true
truecolor: true
enable_ansi_colors: None
is_ci: false
```

**Comment by max-sixty** [comment]
Perfect! Closing this, can reopen if anything comes up on the issue per se
