### ISSUE TITLE
NO_COLOR precedence

### ISSUE THREAD

**Issue by bluss** [rust-cli/anstyle#178]
This document https://bixense.com/clicolors/ says that NO_COLOR has precedence over CLICOLOR_FORCE, but the AutoStream implementation is the other way around.

**Comment by epage** [comment]
The implementation was made before those specs were merged so I had to take a guess.

**Comment by epage** [comment]
Hmm, they've made breaking changes to the spec, changing from value checks to presence checks.  I strongly disagree with what they've changed it to but not really much to be done.

**Comment by epage** [comment]
Compare
```python
def has_colors():
    if ((os.getenv("CLICOLOR", "1") != "0" and sys.stdout.isatty()) or
        os.getenv("CLICOLOR_FORCE", "0") != "0"):
        return True
    else:
        return False
```
with
```python
def has_colors():
    if "NO_COLOR" in os.environ:
        return False
    if "CLICOLOR_FORCE" in os.environ:
        return True
    return sys.stdout.isatty()
```

**Comment by bluss** [comment]
I don't have much of an opinion here, and I didn't know those specs 30 minutes ago - so no need to listen to me. I looked at them because they are linked in rustdoc. Now we know that there is this discrepancy.
