### ISSUE TITLE
Please add copyright and license

### ISSUE THREAD

**Issue by nacho** [rust-cli/anstyle#209]
Please consider adding the license and copyright files to properly track attributions

**Comment by epage** [comment]
Could you be more specific about what is missing?

Each crate should have a `LICENSE-MIT` and `LICENSE-APACHE`.

Unsure what you are looking for for copyright.  From my understanding, we don't do copyright assignment, so the copyright is held by each contributor for what they contribute.  Tracking that is best left to git history than trying to manually annotate each person's claim on copyright.

**Comment by nacho** [comment]
Right, I was initially looking at the license on the root directory and then I realized that it was per crate. Thanks!
