### ISSUE TITLE
anstyle-query's term_supports_ansi_color isn't quite right on Windows

### ISSUE THREAD

**Issue by sunshowers** [rust-cli/anstyle#210]
Hey!

I was checking out anstyle-query and saw this bit of code:

https://github.com/rust-cli/anstyle/blob/4b8b9c59901ad5c08191303b59645c0139240acb/crates/anstyle-query/src/lib.rs#L97-L99

I checked both conhost.exe and Windows Terminal and neither of them set `TERM`. But they do support ANSI colors on all versions of Windows 10 after 1511, so returning `false` isn't quite right.

I guess this makes sense for anstream, which can fall back to Windows console library calls, but if some other crate decides to use anstyle-query and only supports ANSI colors then they're going to get a misleading answer sadly.

**Comment by epage** [comment]
From how I use that check, I think we have different expectations for it.  I treat `term_supports_ansi_color` as "does this terminal natively support ANSI color codes" and require people to separately check `enable_ansi_colors` for "can I change this terminal to support ansi color codes".

https://github.com/rust-cli/anstyle/blob/4b8b9c59901ad5c08191303b59645c0139240acb/crates/anstream/src/auto.rs#L112-L122

**Comment by sunshowers** [comment]
Oh I see! That makes sense then. But yeah it definitely didn't match my expectations of how that function works.

**Comment by sunshowers** [comment]
I guess it might be worth updating the comment because it's not actually strange that TERM isn't set on Windows — only things like mintty set it.

**Comment by epage** [comment]
Wow, looks like I butchered `termcolor`s code, applying comments in cases they didn't apply.  Made improvements in #212.

**Comment by sunshowers** [comment]
All right, I think this looks good. Thanks!
