### ISSUE TITLE
Feature Request: Support serde `Serialize` and `Deserialize` for `Color` enum

### ISSUE THREAD

**Issue by WillLillis** [rust-cli/anstyle#218]
I'm working on a feature that uses the `Color` enum as configuration values. I'd like to be able to serialize/deserialize these values so that they can be read from/written to a file. I did a quick search through the old issues/PRs and didn't see any push against this. I already implemented this in the [serde branch](https://github.com/WillLillis/anstyle/tree/serde), and am happy to open a PR if that would be helpful. Thanks for such a great project! :)

**Comment by epage** [comment]
`anstyle` intentionally does not cover any case beyond passing style information between APIs.  Other crates handle serialization / deserialization strategies, like `anstyle-ls` and `anstyle-git`.  This avoids having to to define a bespoke format that ties into the compatibility story for `anstyle` to reduce the risk of ever needing to go 2.0.

If there is another a common terminal style description format that we do not support, we would welcome discussion of it in a dedicated issue.
